# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b92f848ee4e0af2e8b6139eaf6c74c8f62847429fa83480279b0cfe2131c22ca2f4cf4b70c1d45d6c58d90e41ea51c25d72a1f1f01a6feb9b10f7179be8b642

test:
  secret_key_base: ee404cfa3ba66134d0b5afe6341099e989bb34958f1f49e23ad90a2c6c25419f288cd95c110293a28677e26e31a42df796e3133f602b0e14a59abf8991f4c290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
